-- luacheck: ignore 631

Schema.voices.Add("콤바인", "0", "0.", "npc/metropolice/vo/zero.wav")
Schema.voices.Add("콤바인", "1", "1.", "npc/metropolice/vo/one.wav")
Schema.voices.Add("콤바인", "10", "10.", "npc/metropolice/vo/ten.wav")
Schema.voices.Add("콤바인", "10-0 수색 중", "10-0, 맨핵이 수색 중이다!", "npc/metropolice/vo/tenzerovisceratorishunting.wav")
Schema.voices.Add("콤바인", "100", "100.", "npc/metropolice/vo/onehundred.wav")
Schema.voices.Add("콤바인", "10-103 예상", "10-103 예상, 후방 병력에 알려라.", "npc/metropolice/vo/possible10-103alerttagunits.wav")
Schema.voices.Add("콤바인", "10-107", "10-107 포착됐다, 공중 공격 요청한다.", "npc/metropolice/vo/gota10-107sendairwatch.wav")
Schema.voices.Add("콤바인", "10-108", "10-108 상황 발생!", "npc/metropolice/vo/wehavea10-108.wav")
Schema.voices.Add("콤바인", "10-14", "10-14 근무 중, 코드 4.", "npc/metropolice/vo/holdingon10-14duty.wav")
Schema.voices.Add("콤바인", "10-15", "10-15 준비하라.", "npc/metropolice/vo/preparefor1015.wav")
Schema.voices.Add("콤바인", "10-2", "10-2.", "npc/metropolice/vo/ten2.wav")
Schema.voices.Add("콤바인", "10-25", "아무 병력, 10-25 용의자 보고하라.", "npc/metropolice/vo/unitreportinwith10-25suspect.wav")
Schema.voices.Add("콤바인", "10-30", "10-20에 10-30이 있다, 코드 2 진행하겠다.", "npc/metropolice/vo/Ihave10-30my10-20responding.wav")
Schema.voices.Add("콤바인", "10-4", "10-4.", "npc/metropolice/vo/ten4.wav")
Schema.voices.Add("콤바인", "10-65", "병력은 10-65 상태.", "npc/metropolice/vo/unitis10-65.wav")
Schema.voices.Add("콤바인", "10-78", "10-78 지원, 대원이 위험하다!", "npc/metropolice/vo/dispatchIneed10-78.wav")
Schema.voices.Add("콤바인", "10-8", "10-8, 대기 중.", "npc/metropolice/vo/ten8standingby.wav")
Schema.voices.Add("콤바인", "10-8 수행 중", "병력은 10-8, 수행 중.", "npc/metropolice/vo/unitisonduty10-8.wav")
Schema.voices.Add("콤바인", "10-91", "10-91 사망자 수는...", "npc/metropolice/vo/ten91dcountis.wav")
Schema.voices.Add("콤바인", "10-97 GOA", "10-97, 용의자는 GOA 상태.", "npc/metropolice/vo/ten97suspectisgoa.wav")
Schema.voices.Add("콤바인", "10-97", "10-97.", "npc/metropolice/vo/ten97.wav")
Schema.voices.Add("콤바인", "10-99", "경찰이 쓰러졌다, 여기는 10-99!", "npc/metropolice/vo/officerdownIam10-99.wav")
Schema.voices.Add("콤바인", "11-44", "11-44 데려와라, 지금 소탕한다.", "npc/metropolice/vo/get11-44inboundcleaningup.wav")
Schema.voices.Add("콤바인", "11-6", "용의자 11-6, 여기는 10-20.", "npc/metropolice/vo/suspect11-6my1020is.wav")
Schema.voices.Add("콤바인", "11-99", "11-99, 긴급 지원 바란다!", "npc/metropolice/vo/11-99officerneedsassistance.wav")
Schema.voices.Add("콤바인", "2", "2.", "npc/metropolice/vo/two.wav")
Schema.voices.Add("콤바인", "20", "20.", "npc/metropolice/vo/twenty.wav")
Schema.voices.Add("콤바인", "200", "200.", "npc/metropolice/vo/twohundred.wav")
Schema.voices.Add("콤바인", "3", "3.", "npc/metropolice/vo/three.wav")
Schema.voices.Add("콤바인", "30", "30.", "npc/metropolice/vo/thirty.wav")
Schema.voices.Add("콤바인", "300", "300.", "npc/metropolice/vo/threehundred.wav")
Schema.voices.Add("콤바인", "34S", "모든 병력 주의하라, 34-S 발생.", "npc/metropolice/vo/allunitsbol34sat.wav")
Schema.voices.Add("콤바인", "4", "4.", "npc/metropolice/vo/four.wav")
Schema.voices.Add("콤바인", "40", "40.", "npc/metropolice/vo/fourty.wav")
Schema.voices.Add("콤바인", "404", "404 구역.", "npc/metropolice/vo/404zone.wav")
Schema.voices.Add("콤바인", "408", "이곳에 408 사태 발생했다.", "npc/metropolice/vo/Ivegot408hereatlocation.wav")
Schema.voices.Add("콤바인", "415B", "415-B 중.", "npc/metropolice/vo/is415b.wav")
Schema.voices.Add("콤바인", "5", "5.", "npc/metropolice/vo/five.wav")
Schema.voices.Add("콤바인", "50", "50.", "npc/metropolice/vo/fifty.wav")
Schema.voices.Add("콤바인", "505", "공중 추적 지원 바람, 표적 505!", "npc/metropolice/vo/airwatchsubjectis505.wav")
Schema.voices.Add("콤바인", "6", "6.", "npc/metropolice/vo/six.wav")
Schema.voices.Add("콤바인", "60", "60.", "npc/metropolice/vo/sixty.wav")
Schema.voices.Add("콤바인", "603", "603, 불법 침입.", "npc/metropolice/vo/unlawfulentry603.wav")
Schema.voices.Add("콤바인", "63", "63, 비인가 구역 침입.", "npc/metropolice/vo/criminaltrespass63.wav")
Schema.voices.Add("콤바인", "7", "7.", "npc/metropolice/vo/seven.wav")
Schema.voices.Add("콤바인", "70", "70.", "npc/metropolice/vo/seventy.wav")
Schema.voices.Add("콤바인", "8", "8.", "npc/metropolice/vo/eight.wav")
Schema.voices.Add("콤바인", "80", "80.", "npc/metropolice/vo/eighty.wav")
Schema.voices.Add("콤바인", "9", "9.", "npc/metropolice/vo/nine.wav")
Schema.voices.Add("콤바인", "90", "90.", "npc/metropolice/vo/ninety.wav")
Schema.voices.Add("콤바인", "수류탄!", "수류탄이다!", "npc/metropolice/vo/thatsagrenade.wav")
Schema.voices.Add("콤바인", "용의자 포착", "용의자 포착됐다!", "npc/metropolice/vo/acquiringonvisual.wav")
Schema.voices.Add("콤바인", "지급하라", "지급하라.", "npc/metropolice/vo/administer.wav")
Schema.voices.Add("콤바인", "용의자 무기 소지", "해당 용의자의 무기 소지 확인, 10-0.", "npc/metropolice/vo/confirmadw.wav")
Schema.voices.Add("콤바인", "ㅇㅋ", "알았다.", "npc/metropolice/vo/affirmative.wav")
Schema.voices.Add("콤바인", "진입하라", "모든 병력, 진입하라!", "npc/metropolice/vo/allunitsmovein.wav")
Schema.voices.Add("콤바인", "절단", "절단.", "npc/metropolice/vo/amputate.wav")
Schema.voices.Add("콤바인", "반시민", "반-시민.", "npc/metropolice/vo/anticitizen.wav")
Schema.voices.Add("콤바인", "소독제", "소독제.", "npc/combine_soldier/vo/antiseptic.wav")
Schema.voices.Add("콤바인", "에이펙스", "에이펙스.", "npc/combine_soldier/vo/apex.wav")
Schema.voices.Add("콤바인", "적용", "적용.", "npc/metropolice/vo/apply.wav")
Schema.voices.Add("콤바인", "구속 위치", "모든 병력, 구속 위치로 이동하라!", "npc/metropolice/vo/movetoarrestpositions.wav")
Schema.voices.Add("콤바인", "검문소", "검문소.", "npc/metropolice/vo/atcheckpoint.wav")
Schema.voices.Add("콤바인", "위치 도착", "보호 기동대 위치 도착. 보고한다.", "npc/metropolice/vo/ptatlocationreport.wav")
Schema.voices.Add("콤바인", "엄호나감", "엄호하라, 나간다!", "npc/metropolice/vo/backmeupImout.wav")
Schema.voices.Add("콤바인", "지원", "지원!", "npc/metropolice/vo/backup.wav")
Schema.voices.Add("콤바인", "블레이드", "블레이드.", "npc/combine_soldier/vo/blade.wav")
Schema.voices.Add("콤바인", "용의자 다침", "용의자, 상처 입고 피를 흘리고 있다!", "npc/metropolice/vo/suspectisbleeding.wav")
Schema.voices.Add("콤바인", "소탕하라", "기기에 포착된 범죄 현장을 소탕하라.", "npc/metropolice/vo/catchthatbliponstabilization.wav")
Schema.voices.Add("콤바인", "단결", "구역 유지 중, 단결.", "npc/metropolice/vo/blockisholdingcohesive.wav")
Schema.voices.Add("콤바인", "블록", "블록.", "npc/metropolice/vo/block.wav")
Schema.voices.Add("콤바인", "243", "243 수색 지원할 공중 추적 바람.", "npc/metropolice/vo/cpbolforthat243.wav")
Schema.voices.Add("콤바인", "폭발물", "폭발물.", "npc/combine_soldier/vo/boomer.wav")
Schema.voices.Add("콤바인", "엄페물 제거", "엄폐물 제거하라!", "npc/metropolice/vo/breakhiscover.wav")
Schema.voices.Add("콤바인", "캔1", "저 캔을 집어라.", "npc/metropolice/vo/pickupthecan1.wav")
Schema.voices.Add("콤바인", "캔2", "저 캔을 집으라고 했다.", "npc/metropolice/vo/pickupthecan3.wav")
Schema.voices.Add("콤바인", "캔3", "이제, 휴지통에 넣어라.", "npc/metropolice/vo/putitinthetrash1.wav")
Schema.voices.Add("콤바인", "캔4", '"휴지통에 넣어"라고 말했다!', "npc/metropolice/vo/putitinthetrash2.wav")
Schema.voices.Add("콤바인", "캔5", "네가 넘어트렸잖아, 주워라.", "npc/metropolice/vo/youknockeditover.wav")
Schema.voices.Add("콤바인", "운하", "운하.", "npc/metropolice/vo/canal.wav")
Schema.voices.Add("콤바인", "운하 구역", "운하 구역!", "npc/metropolice/vo/canalblock.wav")
Schema.voices.Add("콤바인", "제거하라", "제거하라.", "npc/metropolice/vo/cauterize.wav")
Schema.voices.Add("콤바인", "불일치 확인", "불일치 없는지 확인하라.", "npc/metropolice/vo/checkformiscount.wav")
Schema.voices.Add("콤바인", "검문소로 이동하라", "지명된 검문소로 이동하라.", "npc/metropolice/vo/proceedtocheckpoints.wav")
Schema.voices.Add("콤바인", "T94-322", "일반 공공 서비스 T94-322에 자원한 시민을 보고한다. 지금 보내도록 하겠다.", "npc/metropolice/vo/citizensummoned.wav")
Schema.voices.Add("콤바인", "시민", "시민.", "npc/metropolice/vo/citizen.wav")
Schema.voices.Add("콤바인", "사상자 분류", "대상 상태를 사상자로 분류하라. 이 구역은 곧 소탕된다.", "npc/metropolice/vo/classifyasdbthisblockready.wav")
Schema.voices.Add("콤바인", "처리했다", "처리했다.", "npc/combine_soldier/vo/cleaned.wav")
Schema.voices.Add("콤바인", "이상 없음 코드 100", "이상 없음, 코드 100.", "npc/metropolice/vo/clearandcode100.wav")
Schema.voices.Add("콤바인", "용의자에 접근하라", "모든 병력, 용의자에 접근하라!", "npc/metropolice/vo/allunitscloseonsuspect.wav")
Schema.voices.Add("콤바인", "접근 중", "접근 중!", "npc/combine_soldier/vo/closing.wav")
Schema.voices.Add("콤바인", "코드 100", "코드 100.", "npc/metropolice/vo/code100.wav")
Schema.voices.Add("콤바인", "코드 2", "모든 병력, 코드 2!", "npc/metropolice/vo/allunitscode2.wav")
Schema.voices.Add("콤바인", "코드 3", "경찰이 쓰러졌다, 모든 병력은 10-20으로!", "npc/metropolice/vo/officerdowncode3tomy10-20.wav")
Schema.voices.Add("콤바인", "코드 7", "코드 7.", "npc/metropolice/vo/code7.wav")
Schema.voices.Add("콤바인", "저주받은 구역", "저주받은 구역!", "npc/metropolice/vo/condemnedzone.wav")
Schema.voices.Add("콤바인", "243 포착", "243 용의자 포착했다, 10-20.", "npc/metropolice/vo/contactwith243suspect.wav")
Schema.voices.Add("콤바인", "중요도 2 발견", "중요도 2 용의자 발견!", "npc/metropolice/vo/contactwithpriority2.wav")
Schema.voices.Add("콤바인", "포착", "포착!", "npc/combine_soldier/vo/contact.wav")
Schema.voices.Add("콤바인", "격리되었다", "격리되었다.", "npc/combine_soldier/vo/contained.wav")
Schema.voices.Add("콤바인", "647E 없음", "이 구역은 아무 이상이 없다, 647-E 보이지 않는다.", "npc/metropolice/vo/control100percent.wav")
Schema.voices.Add("콤바인", "구역 통제", "구역 통제!", "npc/metropolice/vo/controlsection.wav")
Schema.voices.Add("콤바인", "확인 바람", "확인 바람.", "npc/metropolice/vo/copy.wav")
Schema.voices.Add("콤바인", "엄호하라", "엄호하라!", "npc/combine_soldier/vo/coverhurt.wav")
Schema.voices.Add("콤바인", "CP 연루됨", "CP 연루돼 있다, 지원하라!", "npc/metropolice/vo/cpiscompromised.wav")
Schema.voices.Add("콤바인", "구축 요청", "지역 구축 요청한다, 위치는...", "npc/metropolice/vo/cpweneedtoestablishaperimeterat.wav")
Schema.voices.Add("콤바인", "CP 침략됨", "CP가 침략되었다, 봉쇄가 무너졌다!", "npc/metropolice/vo/cpisoverrunwehavenocontainment.wav")
Schema.voices.Add("콤바인", "대거", "대거.", "npc/combine_soldier/vo/dagger.wav")
Schema.voices.Add("콤바인", "-", "-", "npc/combine_soldier/vo/dash.wav")
Schema.voices.Add("콤바인", "사망자 수", "사망자 수.", "npc/metropolice/vo/dbcountis.wav")
Schema.voices.Add("콤바인", "디펜더", "디펜더.", "npc/metropolice/vo/defender.wav")
Schema.voices.Add("콤바인", "관할 구역", "관할 구역.", "npc/metropolice/vo/deservicedarea.wav")
Schema.voices.Add("콤바인", "용의자 지명", "용의자 지명.", "npc/metropolice/vo/designatesuspectas.wav")
Schema.voices.Add("콤바인", "엄폐물 파괴하라", "엄폐물 파괴하라!", "npc/metropolice/vo/destroythatcover.wav")
Schema.voices.Add("콤바인", "분산시켜라", "사이를 쏴서 힘을 분산시켜라!", "npc/metropolice/vo/firetodislocateinterpose.wav")
Schema.voices.Add("콤바인", "바리케이드 철수 중", "바리케이트 철수 중.", "npc/metropolice/vo/dismountinghardpoint.wav")
Schema.voices.Add("콤바인", "사진", "사진을 갱신 중이다.", "npc/metropolice/vo/dispupdatingapb.wav")
Schema.voices.Add("콤바인", "유통 구역", "유통 구역.", "npc/metropolice/vo/distributionblock.wav")
Schema.voices.Add("콤바인", "기록", "기록.", "npc/metropolice/vo/document.wav")
Schema.voices.Add("콤바인", "동작 그만", "동작 그만!", "npc/metropolice/vo/dontmove.wav")
Schema.voices.Add("콤바인", "에코", "에코.", "npc/combine_soldier/vo/echo.wav")
Schema.voices.Add("콤바인", "수행 중", "수행 중!", "npc/combine_soldier/vo/engaging.wav")
Schema.voices.Add("콤바인", "후퇴", "후퇴하라, 새 CP를 구축하라!", "npc/metropolice/vo/establishnewcp.wav")
Schema.voices.Add("콤바인", "쏴라", "목표를 향해 쏴라!", "npc/metropolice/vo/firingtoexposetarget.wav")
Schema.voices.Add("콤바인", "외부 관할권", "외부 관할권.", "npc/metropolice/vo/externaljurisdiction.wav")
Schema.voices.Add("콤바인", "최종 평결", "최종 평결, 집행 완료.", "npc/metropolice/vo/finalverdictadministered.wav")
Schema.voices.Add("콤바인", "경고3", "최종 경고!", "npc/metropolice/vo/finalwarning.wav")
Schema.voices.Add("콤바인", "ㅂㅋ", "첫번째 경고다, 비켜라!", "npc/metropolice/vo/firstwarningmove.wav")
Schema.voices.Add("콤바인", "피스트", "피스트.", "npc/combine_soldier/vo/fist.wav")
Schema.voices.Add("콤바인", "플래시", "플래시.", "npc/combine_soldier/vo/flash.wav")
Schema.voices.Add("콤바인", "폭스트롯", "폭스트롯.", "npc/combine_soldier/vo/flatline.wav")
Schema.voices.Add("콤바인", "격퇴", "격퇴.", "npc/combine_soldier/vo/flush.wav")
Schema.voices.Add("콤바인", "네크로틱2", "네크로틱이 날뛰고 있다!", "npc/metropolice/vo/freenecrotics.wav")
Schema.voices.Add("콤바인", "숙여", "숙여!", "npc/metropolice/vo/getdown.wav")
Schema.voices.Add("콤바인", "나가", "이제 여기서 나가라.", "npc/metropolice/vo/getoutofhere.wav")
Schema.voices.Add("콤바인", "647E 포착 중", "로컬 감시조에서 647-E를 포착 중.", "npc/metropolice/vo/stillgetting647e.wav")
Schema.voices.Add("콤바인", "고스트", "고스트.", "npc/combine_soldier/vo/ghost.wav")
Schema.voices.Add("콤바인", "다시ㄱ", "PT, 다시 가라.", "npc/metropolice/vo/ptgoagain.wav")
Schema.voices.Add("콤바인", "ㄱㄱ", "이동하라!", "npc/combine_soldier/vo/gosharp.wav")
Schema.voices.Add("콤바인", "엄호들감", "엄호하라, 들어간다!", "npc/metropolice/vo/covermegoingin.wav")
Schema.voices.Add("콤바인", "시체 발견", "시체 발견, 11-42 취소하라.", "npc/metropolice/vo/wegotadbherecancel10-102.wav")
Schema.voices.Add("콤바인", "다시 포착했다", "다시 포착했다. 용의자 위치, 10-20.", "npc/metropolice/vo/gothimagainsuspect10-20at.wav")
Schema.voices.Add("콤바인", "공범자 잡았다", "여기 공범자 한 명 잡았다!", "npc/metropolice/vo/gotoneaccomplicehere.wav")
Schema.voices.Add("콤바인", "용의자1 잡았다", "여기 용의자 1 잡았다!", "npc/metropolice/vo/gotsuspect1here.wav")
Schema.voices.Add("콤바인", "수류탄", "수류탄!", "npc/metropolice/vo/grenade.wav")
Schema.voices.Add("콤바인", "그리드", "그리드.", "npc/combine_soldier/vo/grid.wav")
Schema.voices.Add("콤바인", "ㅋㅋ", "*(조용한 웃음소리)*", "npc/metropolice/vo/chuckle.wav")
Schema.voices.Add("콤바인", "해머", "해머.", "npc/combine_soldier/vo/hammer.wav")
Schema.voices.Add("콤바인", "현장 도착", "현장에 도착했다, 준비 완료!", "npc/metropolice/vo/isathardpointreadytoprosecute.wav")
Schema.voices.Add("콤바인", "현장 수색", "현장 수색 중.", "npc/metropolice/vo/hardpointscanning.wav")
Schema.voices.Add("콤바인", "헬릭스", "헬릭스", "npc/combine_soldier/vo/helix.wav")
Schema.voices.Add("콤바인", "도와줘", "도와줘!", "npc/metropolice/vo/help.wav")
Schema.voices.Add("콤바인", "히어로", "히어로.", "npc/metropolice/vo/hero.wav")
Schema.voices.Add("콤바인", "148", "148 코드 발생!", "npc/metropolice/vo/hesgone148.wav")
Schema.voices.Add("콤바인", "중요 지역", "중요 지역.", "npc/metropolice/vo/highpriorityregion.wav")
Schema.voices.Add("콤바인", "ㄱㄷ", "거기서 멈춰라!", "npc/metropolice/vo/holditrightthere.wav")
Schema.voices.Add("콤바인", "위치 사수", "보호 기동대, 이 위치를 사수하라.", "npc/metropolice/vo/holdthisposition.wav")
Schema.voices.Add("콤바인", "멈춰라", "멈춰라!", "npc/metropolice/vo/holdit.wav")
Schema.voices.Add("콤바인", "헌터", "헌터.", "npc/combine_soldier/vo/hunter.wav")
Schema.voices.Add("콤바인", "허리케인", "허리케인.", "npc/combine_soldier/vo/hurricane.wav")
Schema.voices.Add("콤바인", "움직여2", "움직이라고 말했다.", "npc/metropolice/vo/Isaidmovealong.wav")
Schema.voices.Add("콤바인", "아이스", "아이스.", "npc/combine_soldier/vo/ice.wav")
Schema.voices.Add("콤바인", "ㄹㄷ", "준비됐다.", "npc/metropolice/vo/inposition.wav")
Schema.voices.Add("콤바인", "접근", "접근.", "npc/combine_soldier/vo/inbound.wav")
Schema.voices.Add("콤바인", "감염 확인", "감염 확인.", "npc/combine_soldier/vo/infected.wav")
Schema.voices.Add("콤바인", "감염", "감염!", "npc/metropolice/vo/infection.wav")
Schema.voices.Add("콤바인", "감염된 구역", "감염된 구역.", "npc/metropolice/vo/infestedzone.wav")
Schema.voices.Add("콤바인", "주입", "주입!", "npc/metropolice/vo/inject.wav")
Schema.voices.Add("콤바인", "투입", "투입.", "npc/metropolice/vo/innoculate.wav")
Schema.voices.Add("콤바인", "차단", "차단!", "npc/metropolice/vo/intercede.wav")
Schema.voices.Add("콤바인", "결합", "결합!", "npc/metropolice/vo/interlock.wav")
Schema.voices.Add("콤바인", "조사", "조사.", "npc/metropolice/vo/investigate.wav")
Schema.voices.Add("콤바인", "조사 중", "10-103 조사 중.", "npc/metropolice/vo/investigating10-103.wav")
Schema.voices.Add("콤바인", "이온", "이온.", "npc/combine_soldier/vo/ion.wav")
Schema.voices.Add("콤바인", "10-108 발생", "10-108 발생!", "npc/metropolice/vo/is10-108.wav")
Schema.voices.Add("콤바인", "10-8 대기 중", "병력은 10-8, 대기 중.", "npc/metropolice/vo/unitis10-8standingby.wav")
Schema.voices.Add("콤바인", "접근 중3", "용의자에 접근 중!", "npc/metropolice/vo/isclosingonsuspect.wav")
Schema.voices.Add("콤바인", "쓰러졌다", "쓰러졌다!", "npc/metropolice/vo/isdown.wav")
Schema.voices.Add("콤바인", "도착 중", "병력 도착 중.", "npc/combine_soldier/vo/unitisinbound.wav")
Schema.voices.Add("콤바인", "이동 중", "병력 이동 중.", "npc/combine_soldier/vo/unitismovingin.wav")
Schema.voices.Add("콤바인", "접근 중2", "접근 중이다!", "npc/metropolice/vo/ismovingin.wav")
Schema.voices.Add("콤바인", "무반응", "반응이 없다.", "npc/metropolice/vo/ispassive.wav")
Schema.voices.Add("콤바인", "ㄹㄷ2", "준비가 됬다!", "npc/metropolice/vo/isreadytogo.wav")
Schema.voices.Add("콤바인", "격리", "격리!", "npc/metropolice/vo/isolate.wav")
Schema.voices.Add("콤바인", "제트", "제트.", "npc/combine_soldier/vo/jet.wav")
Schema.voices.Add("콤바인", "저지", "저지.", "npc/combine_soldier/vo/judge.wav")
Schema.voices.Add("콤바인", "판결", "용의자, 판결을 받을 준비를 하라!", "npc/metropolice/vo/prepareforjudgement.wav")
Schema.voices.Add("콤바인", "진압 관할권", "진압 관할권.", "npc/metropolice/vo/stabilizationjurisdiction.wav")
Schema.voices.Add("콤바인", "주리", "주리.", "npc/metropolice/vo/jury.wav")
Schema.voices.Add("콤바인", "계속 움직여라", "계속 움직여라!", "npc/metropolice/vo/keepmoving.wav")
Schema.voices.Add("콤바인", "킬로", "킬로.", "npc/combine_soldier/vo/kilo.wav")
Schema.voices.Add("콤바인", "킹", "킹.", "npc/metropolice/vo/king.wav")
Schema.voices.Add("콤바인", "마지막 포착 위치", "의심 중, 마지막 포착 위치.", "npc/metropolice/vo/hidinglastseenatrange.wav")
Schema.voices.Add("콤바인", "리더", "리더.", "npc/combine_soldier/vo/leader.wav")
Schema.voices.Add("콤바인", "레벨 3", "여기에 레벨 3 시민 사생활 침해자가 있다!", "npc/metropolice/vo/level3civilprivacyviolator.wav")
Schema.voices.Add("콤바인", "정렬", "정렬.", "npc/metropolice/vo/line.wav")
Schema.voices.Add("콤바인", "위치", "위치?", "npc/metropolice/vo/location.wav")
Schema.voices.Add("콤바인", "위치 사수", "모든 병력, 위치를 사수하라!", "npc/metropolice/vo/lockyourposition.wav")
Schema.voices.Add("콤바인", "사수", "사수!", "npc/metropolice/vo/lock.wav")
Schema.voices.Add("콤바인", "조심", "조심해!", "npc/metropolice/vo/lookout.wav")
Schema.voices.Add("콤바인", "기생충 조심", "기생충 조심하라!", "npc/metropolice/vo/looseparasitics.wav")
Schema.voices.Add("콤바인", "추적 실패", "추적 실패!", "npc/combine_soldier/vo/lostcontact.wav")
Schema.voices.Add("콤바인", "실탄 부족", "실탄이 부족하다, 엄폐하겠다!", "npc/metropolice/vo/runninglowonverdicts.wav")
Schema.voices.Add("콤바인", "메이스", "메이스.", "npc/combine_soldier/vo/mace.wav")
Schema.voices.Add("콤바인", "CP 사수", "모든 병력, 이 CP 사수하라!", "npc/metropolice/vo/allunitsmaintainthiscp.wav")
Schema.voices.Add("콤바인", "불순종", "불순종 소환장 발행 중.", "npc/metropolice/vo/issuingmalcompliantcitation.wav")
Schema.voices.Add("콤바인", "10-107 불순종", "10-20에서 10-107의 불순종, 구속 진행.", "npc/metropolice/vo/malcompliant10107my1020.wav")
Schema.voices.Add("콤바인", "악성", "악성!", "npc/metropolice/vo/malignant.wav")
Schema.voices.Add("콤바인", "사진 일치", "APB 사진과 일치한다.", "npc/metropolice/vo/matchonapblikeness.wav")
Schema.voices.Add("콤바인", "경미한 부상", "경미한 부상이다, 임무 재개 중!", "npc/metropolice/vo/minorhitscontinuing.wav")
Schema.voices.Add("콤바인", "움직여", "움직여!", "npc/metropolice/vo/move.wav")
Schema.voices.Add("콤바인", "ㅂㅋ2", "즉시 물러나라!", "npc/metropolice/vo/movebackrightnow.wav")
Schema.voices.Add("콤바인", "진입하라", "진입하라!", "npc/combine_soldier/vo/movein.wav")
Schema.voices.Add("콤바인", "엄호 이동", "엄호 위치로 이동한다!", "npc/metropolice/vo/movingtocover.wav")
Schema.voices.Add("콤바인", "현장 이동", "현장으로 이동한다!", "npc/metropolice/vo/movingtohardpoint.wav")
Schema.voices.Add("콤바인", "네크로틱", "네크로틱!", "npc/metropolice/vo/necrotics.wav")
Schema.voices.Add("콤바인", "지원이 필요한가", "지원이 필요한가?", "npc/metropolice/vo/needanyhelpwiththisone.wav")
Schema.voices.Add("콤바인", "부상", "부상 당한 경찰이 있다, 11-99!", "npc/metropolice/vo/officerneedsassistance.wav")
Schema.voices.Add("콤바인", "지원 요청", "경찰이 지원 요청한다!", "npc/metropolice/vo/officerneedshelp.wav")
Schema.voices.Add("콤바인", "10-107 없음", "이상 없음, 10-107 없음.", "npc/metropolice/vo/clearno647no10-107.wav")
Schema.voices.Add("콤바인", "시야 미확보", "시야 미확보!", "npc/metropolice/vo/nocontact.wav")
Schema.voices.Add("콤바인", "ㄱㅊ", "아니, 괜찮아.", "vo/trainyard/ba_noimgood.wav")
Schema.voices.Add("콤바인", "용의자 안보임", "현재 용의자가 보이지 않는다.", "npc/metropolice/vo/novisualonupi.wav")
Schema.voices.Add("콤바인", "노매드", "노매드.", "npc/combine_soldier/vo/nomad.wav")
Schema.voices.Add("콤바인", "비감시", "비감시 영역.", "npc/metropolice/vo/nonpatrolregion.wav")
Schema.voices.Add("콤바인", "태그 없는 바이롬", "태그 없는 바이롬을 발견했다!", "npc/metropolice/vo/non-taggedviromeshere.wav")
Schema.voices.Add("콤바인", "노바", "노바.", "npc/combine_soldier/vo/nova.wav")
Schema.voices.Add("콤바인", "ㅇㅋ2", "좋아.", "vo/trainyard/ba_thatbeer01.wav")
Schema.voices.Add("콤바인", "확산", "확산!", "npc/combine_soldier/vo/outbreak.wav")
Schema.voices.Add("콤바인", "보고한다", "보고한다.", "npc/combine_soldier/vo/overwatch.wav")
Schema.voices.Add("콤바인", "진압 중", "진압 중!", "npc/metropolice/vo/pacifying.wav")
Schema.voices.Add("콤바인", "고통", "*고통에 찬 소리*", "npc/metropolice/pain1.wav")
Schema.voices.Add("콤바인", "고통2", "*고통에 찬 소리*", "npc/metropolice/pain2.wav")
Schema.voices.Add("콤바인", "고통3", "*고통에 찬 소리*", "npc/metropolice/pain3.wav")
Schema.voices.Add("콤바인", "고통4", "*고통에 찬 소리*", "npc/metropolice/pain4.wav")
Schema.voices.Add("콤바인", "정찰", "정찰!", "npc/metropolice/vo/patrol.wav")
Schema.voices.Add("콤바인", "보복", "보복.", "npc/combine_soldier/vo/payback.wav")
Schema.voices.Add("콤바인", "팬텀", "팬텀.", "npc/combine_soldier/vo/phantom.wav")
Schema.voices.Add("콤바인", "647E", "647-E 상태를 확인한 사람 또 있나?", "npc/metropolice/vo/anyonepickup647e.wav")
Schema.voices.Add("콤바인", "접전지 위치", "접전지 위치, 준비 완료.", "npc/metropolice/vo/inpositionathardpoint.wav")
Schema.voices.Add("콤바인", "진압 대기 중", "진압 대기 중.", "npc/metropolice/vo/positiontocontain.wav")
Schema.voices.Add("콤바인", "404 예상", "여기에 404 발생 예상!", "npc/metropolice/vo/possible404here.wav")
Schema.voices.Add("콤바인", "647E 예상", "647-E 상황 예상, 공중 추적 요청한다.", "npc/metropolice/vo/possible647erequestairwatch.wav")
Schema.voices.Add("콤바인", "공범자", "공범자로 의심되는 자를 보고한다.", "npc/metropolice/vo/reportsightingsaccomplices.wav")
Schema.voices.Add("콤바인", "레벨 3 예상", "레벨 3 시민 사생활 침해자가 있다!", "npc/metropolice/vo/possiblelevel3civilprivacyviolator.wav")
Schema.voices.Add("콤바인", "판결 준비 중", "10-107, 판결을 준비 중이다.", "npc/metropolice/vo/preparingtojudge10-107.wav")
Schema.voices.Add("콤바인", "보호", "보호!", "npc/metropolice/vo/preserve.wav")
Schema.voices.Add("콤바인", "압력", "압력!", "npc/metropolice/vo/pressure.wav")
Schema.voices.Add("콤바인", "중요도 1", "중요도 1 용의자 발견했다.", "npc/metropolice/vo/confirmpriority1sighted.wav")
Schema.voices.Add("콤바인", "중요도 2", "여기에 중요도 2 반시민이 있다!", "npc/metropolice/vo/priority2anticitizenhere.wav")
Schema.voices.Add("콤바인", "생산 구역", "생산 구역.", "npc/metropolice/vo/productionblock.wav")
Schema.voices.Add("콤바인", "기소 준비", "불순종 시민, 기소 준비를 마쳤다!", "npc/metropolice/vo/readytoprosecutefinalwarning.wav")
Schema.voices.Add("콤바인", "수행", "수행!", "npc/metropolice/vo/prosecute.wav")
Schema.voices.Add("콤바인", "수행 중", "수행 중.", "npc/combine_soldier/vo/prosecuting.")
Schema.voices.Add("콤바인", "보호 완료", "보호 완료.", "npc/metropolice/vo/protectioncomplete.wav")
Schema.voices.Add("콤바인", "퀵", "퀵!", "npc/metropolice/vo/quick.wav")
Schema.voices.Add("콤바인", "퀘벡", "퀘벡.", "npc/combine_soldier/vo/quicksand.wav")
Schema.voices.Add("콤바인", "범위", "범위:", "npc/combine_soldier/vo/range.wav")
Schema.voices.Add("콤바인", "레인저", "레인저.", "npc/combine_soldier/vo/ranger.wav")
Schema.voices.Add("콤바인", "레이저", "레이저.", "npc/combine_soldier/vo/razor.wav")
Schema.voices.Add("콤바인", "절단 준비", "절단 준비 완료!", "npc/metropolice/vo/readytoamputate.wav")
Schema.voices.Add("콤바인", "포격 준비", "포격 준비!", "npc/combine_soldier/vo/readycharges.wav")
Schema.voices.Add("콤바인", "판결 준비", "판결 준비 완료.", "npc/metropolice/vo/readytojudge.wav")
Schema.voices.Add("콤바인", "속행 준비", "속행 준비 완료!", "npc/metropolice/vo/readytoprosecute.wav")
Schema.voices.Add("콤바인", "무기 준비", "무기 준비!", "npc/combine_soldier/vo/readyweapons.wav")
Schema.voices.Add("콤바인", "리퍼", "리퍼.", "npc/combine_soldier/vo/reaper.wav")
Schema.voices.Add("콤바인", "지원 팀", "지원 팀, 코드 3!", "npc/metropolice/vo/reinforcementteamscode3.wav")
Schema.voices.Add("콤바인", "이상 없음", "이상 없음.", "npc/combine_soldier/vo/reportingclear.wav")
Schema.voices.Add("콤바인", "보고하라", "모든 병력, 위치 요청한다. 보고하라.", "npc/metropolice/vo/cprequestsallunitsreportin.wav")
Schema.voices.Add("콤바인", "용의자 위치 보고", "모든 병력, 용의자 위치 보고하라!", "npc/metropolice/vo/allunitsreportlocationsuspect.wav")
Schema.voices.Add("콤바인", "상황 보고하라", "CP 팀, 상황 보고하라.", "npc/metropolice/vo/localcptreportstatus.wav")
Schema.voices.Add("콤바인", "용도 변경", "용도 변경 지역.", "npc/metropolice/vo/repurposedarea.wav")
Schema.voices.Add("콤바인", "거주 구역", "거주 구역.", "npc/metropolice/vo/residentialblock.wav")
Schema.voices.Add("콤바인", "코드 3 응답", "현장의 모든 병력, 코드 3 응답하라!", "npc/metropolice/vo/allunitsrespondcode3.wav")
Schema.voices.Add("콤바인", "ㅇㅇ", "응답.", "npc/metropolice/vo/responding2.wav")
Schema.voices.Add("콤바인", "제한", "제한!", "npc/metropolice/vo/restrict.wav")
Schema.voices.Add("콤바인", "제한 구역", "제한 구역.", "npc/metropolice/vo/restrictedblock.wav")
Schema.voices.Add("콤바인", "최종 제한 구역", "최종 제한 구역!", "npc/metropolice/vo/terminalrestrictionzone.wav")
Schema.voices.Add("콤바인", "후퇴", "후퇴3", "npc/combine_soldier/vo/ripcord.wav")
Schema.voices.Add("콤바인", "ㅇㅋ오버", "알았다, 오버!", "npc/metropolice/vo/rodgerthat.wav")
Schema.voices.Add("콤바인", "롤러", "롤러!", "npc/metropolice/vo/roller.wav")
Schema.voices.Add("콤바인", "도망간다", "도망가고 있다!", "npc/metropolice/vo/hesrunning.wav")
Schema.voices.Add("콤바인", "코드 무시", "모든 병력, 코드 1 무시하고 이 CP를 사수하라!", "npc/metropolice/vo/sacrificecode1maintaincp.wav")
Schema.voices.Add("콤바인", "새비지", "새비지.", "npc/combine_soldier/vo/savage.wav")
Schema.voices.Add("콤바인", "스카", "스카.", "npc/combine_soldier/vo/scar.wav")
Schema.voices.Add("콤바인", "수색", "수색!", "npc/metropolice/vo/search.wav")
Schema.voices.Add("콤바인", "용의자 찾는 중", "용의자 찾는 중, 상태 없음.", "npc/metropolice/vo/searchingforsuspect.wav")
Schema.voices.Add("콤바인", "경고2", "이것은 두번째 경고다!", "npc/metropolice/vo/thisisyoursecondwarning.wav")
Schema.voices.Add("콤바인", "미살균 확인", "미살균 구역인지 확인하라.", "npc/combine_soldier/vo/confirmsectornotsterile.wav")
Schema.voices.Add("콤바인", "구역 미확보", "구역 미확보.", "npc/combine_soldier/vo/sectorisnotsecure.wav")
Schema.voices.Add("콤바인", "전진하라", "습격 지점 확보, 전진하라!", "npc/metropolice/vo/assaultpointsecureadvance.wav")
Schema.voices.Add("콤바인", "처리 완수", "처리 완수.", "npc/combine_soldier/vo/secure.wav")
Schema.voices.Add("콤바인", "선고되었다", "선고되었다.", "npc/metropolice/vo/sentencedelivered.wav")
Schema.voices.Add("콤바인", "복무", "복무.", "npc/metropolice/vo/serve.wav")
Schema.voices.Add("콤바인", "섀도우", "섀도우.", "npc/combine_soldier/vo/shadow.wav")
Schema.voices.Add("콤바인", "이동 구역", "이동 구역.", "npc/combine_soldier/vo/sharpzone.wav")
Schema.voices.Add("콤바인", "젠장", "젠장!", "npc/metropolice/vo/shit.wav")
Schema.voices.Add("콤바인", "발사", "무기 발사, 적대적인 생명체 발견!", "npc/metropolice/vo/shotsfiredhostilemalignants.wav")
Schema.voices.Add("콤바인", "SLAM", "SLAM.", "npc/combine_soldier/vo/slam.wav")
Schema.voices.Add("콤바인", "슬래시", "슬래시.", "npc/combine_soldier/vo/slash.wav")
Schema.voices.Add("콤바인", "반사회", "반사회.", "npc/metropolice/vo/sociocide.wav")
Schema.voices.Add("콤바인", "안정 지역", "이 지역은 안정되어 있다.", "npc/metropolice/vo/wearesociostablethislocation.wav")
Schema.voices.Add("콤바인", "스피어", "스피어.", "npc/combine_soldier/vo/spear.wav")
Schema.voices.Add("콤바인", "스탭", "스탭.", "npc/combine_soldier/vo/stab.wav")
Schema.voices.Add("콤바인", "대기 중", "대기 중.", "npc/combine_soldier/vo/standingby].wav")
Schema.voices.Add("콤바인", "스타", "스타.", "npc/combine_soldier/vo/star.wav")
Schema.voices.Add("콤바인", "스테이션 구역", "스테이션 구역.", "npc/metropolice/vo/stationblock.wav")
Schema.voices.Add("콤바인", "경비하라", "경비하라.", "npc/combine_soldier/vo/stayalert.wav")
Schema.voices.Add("콤바인", "살균", "살균!", "npc/metropolice/vo/sterilize.wav")
Schema.voices.Add("콤바인", "스팅어", "스팅어.", "npc/combine_soldier/vo/stinger.wav")
Schema.voices.Add("콤바인", "스톰", "스톰.", "npc/combine_soldier/vo/storm.wav")
Schema.voices.Add("콤바인", "스트라이커", "스트라이커.", "npc/combine_soldier/vo/striker.wav")
Schema.voices.Add("콤바인", "대상은 505", "대상은 505!", "npc/metropolice/vo/subjectis505.wav")
Schema.voices.Add("콤바인", "대상 빨라짐", "주목하라, 대상의 이동 속도가 빨라졌다!", "npc/metropolice/vo/subjectisnowhighspeed.wav")
Schema.voices.Add("콤바인", "대상", "대상!", "npc/metropolice/vo/subject.wav")
Schema.voices.Add("콤바인", "시에라", "시에라.", "npc/combine_soldier/vo/sundown.wav")
Schema.voices.Add("콤바인", "용의자 진입함", "용의자가 이 지역에 진입했다.", "npc/metropolice/vo/dispreportssuspectincursion.wav")
Schema.voices.Add("콤바인", "용의자 이동함", "현재 용의자가 이동했다.", "npc/metropolice/vo/supsecthasmovednowto.wav")
Schema.voices.Add("콤바인", "용의자 운하 사용 중", "용의자가 제한된 운하를 사용하고 있다.", "npc/metropolice/vo/suspectusingrestrictedcanals.wav")
Schema.voices.Add("콤바인", "행동정지", "행동 정지.", "npc/metropolice/vo/suspend.wav")
Schema.voices.Add("콤바인", "스위퍼", "스위퍼.", "npc/combine_soldier/vo/sweeper.wav")
Schema.voices.Add("콤바인", "정찰 중", "정찰 중!", "npc/combine_soldier/vo/sweepingin.wav")
Schema.voices.Add("콤바인", "용의자 추적 중", "용의자 추적 중!", "npc/metropolice/vo/sweepingforsuspect.wav")
Schema.voices.Add("콤바인", "스위프트", "스위프트.", "npc/combine_soldier/vo/swift.wav")
Schema.voices.Add("콤바인", "소드", "소드.", "npc/combine_soldier/vo/sword.wav")
Schema.voices.Add("콤바인", "10-91D 출현", "10-91D 출현!", "npc/metropolice/vo/tag10-91d.wav")
Schema.voices.Add("콤바인", "벌레 출현", "벌레 출현!", "npc/metropolice/vo/tagonebug.wav")
Schema.voices.Add("콤바인", "네크로틱 출현", "네크로틱 출현!", "npc/metropolice/vo/tagonenecrotic.wav")
Schema.voices.Add("콤바인", "기생충 출현", "기생충 출현!", "npc/metropolice/vo/tagoneparasitic.wav")
Schema.voices.Add("콤바인", "살펴보겠다", "살펴보고 오겠다!", "npc/metropolice/vo/goingtotakealook.wav")
Schema.voices.Add("콤바인", "엄폐", "엄폐하라!", "npc/metropolice/vo/takecover.wav")
Schema.voices.Add("콤바인", "탭", "탭.", "npc/metropolice/vo/tap.wav")
Schema.voices.Add("콤바인", "목표", "목표.", "npc/combine_soldier/vo/target.wav")
Schema.voices.Add("콤바인", "전진", "팀 위치 도착, 전진!", "npc/metropolice/vo/teaminpositionadvance.wav")
Schema.voices.Add("콤바인", "진압 대기 중2", "진압 팀, 현 위치에서 대기 중이다.", "npc/combine_soldier/vo/stabilizationteamholding.wav")
Schema.voices.Add("콤바인", "저기 있다2", "저기 있다! 위치.", "npc/metropolice/vo/therehegoeshesat.wav")
Schema.voices.Add("콤바인", "저기 있다", "저기 있다!", "npc/metropolice/vo/thereheis.wav")
Schema.voices.Add("콤바인", "트래커", "트래커.", "npc/combine_soldier/vo/tracker.wav")
Schema.voices.Add("콤바인", "통로 구역", "통로 구역.", "npc/metropolice/vo/transitblock.wav")
Schema.voices.Add("콤바인", "문제", "문제를 일으키러 가나?", "npc/metropolice/vo/lookingfortrouble.wav")
Schema.voices.Add("콤바인", "UNDER FIRE", "Officer under fire, taking cover!", "npc/metropolice/vo/officerunderfiretakingcover.wav")
Schema.voices.Add("콤바인", "유니폼", "유니폼.", "npc/combine_soldier/vo/uniform.wav")
Schema.voices.Add("콤바인", "연합", "연합!", "npc/metropolice/vo/union.wav")
Schema.voices.Add("콤바인", "용의자 위치 파악 안됨", "용의자 위치 파악 안됨.", "npc/metropolice/vo/suspectlocationunknown.wav")
Schema.voices.Add("콤바인", "위쪽", "위쪽에 있다!", "npc/metropolice/vo/hesupthere.wav")
Schema.voices.Add("콤바인", "용의자", "용의자.", "npc/metropolice/vo/upi.wav")
Schema.voices.Add("콤바인", "용의자 미발견", "용의자 미발견.", "npc/metropolice/vo/utlsuspect.wav")
Schema.voices.Add("콤바인", "내보내", "시민을 내보내라!", "npc/metropolice/vo/vacatecitizen.wav")
Schema.voices.Add("콤바인", "뱀프", "뱀프.", "npc/combine_soldier/vo/vamp.wav")
Schema.voices.Add("콤바인", "평결", "불순종 죄로 평결을 원하나?", "npc/metropolice/vo/youwantamalcomplianceverdict.wav")
Schema.voices.Add("콤바인", "바이스", "바이스.", "npc/metropolice/vo/vice.wav")
Schema.voices.Add("콤바인", "빅터", "빅터.", "npc/metropolice/vo/victor.wav")
Schema.voices.Add("콤바인", "포착 확인", "포착 확인.", "npc/combine_soldier/vo/contactconfim.wav")
Schema.voices.Add("콤바인", "엑소젠", "엑소젠 발견했다.", "npc/combine_soldier/vo/visualonexogens.wav")
Schema.voices.Add("콤바인", "경고2 발부", "2차 경고 발부!", "npc/metropolice/vo/secondwarning.wav")
Schema.voices.Add("콤바인", "폐수", "폐수.", "npc/metropolice/vo/wasteriver.wav")
Schema.voices.Add("콤바인", "조심해라", "조심해라!", "npc/metropolice/vo/watchit.wav")
Schema.voices.Add("콤바인", "와인더", "와인더.", "npc/combine_soldier/vo/winder.wav")
Schema.voices.Add("콤바인", "인력", "인력 증원.", "npc/metropolice/vo/workforceintake.wav")
Schema.voices.Add("콤바인", "마무리", "됐어, 마무리 해.", "npc/combine_soldier/vo/thatsitwrapitup.wav")
Schema.voices.Add("콤바인", "엑스레이", "엑스레이!", "npc/metropolice/vo/xray.wav")
Schema.voices.Add("콤바인", "옐로", "옐로!", "npc/metropolice/vo/yellow.wav")
Schema.voices.Add("콤바인", "가도 좋다", "좋아. 가도 좋다.", "npc/metropolice/vo/allrightyoucango.wav")
Schema.voices.Add("콤바인", "구역", "구역!", "npc/metropolice/vo/zone.wav")
Schema.voices.Add("콤바인", "잡았다", "그를 잡았다.", "npc/combine_soldier/vo/affirmativewegothimnow.wav")
Schema.voices.Add("콤바인", "경고1", "경고 1.", "npc/combine_soldier/vo/alert1.wav")
Schema.voices.Add("콤바인", "반시민1", "반-시민 1.", "npc/combine_soldier/vo/anticitizenone.wav")
Schema.voices.Add("콤바인", "방향", "방향:", "npc/combine_soldier/vo/bearing.wav")
Schema.voices.Add("콤바인", "도", "도.", "npc/combine_soldier/vo/degrees.wav")
Schema.voices.Add("콤바인", "ㅌㅌ", "흩어져라!", "npc/combine_soldier/vo/displace.wav")
Schema.voices.Add("콤바인", "ㅌㅌ2", "분산하라!", "npc/combine_soldier/vo/displace2.wav")
Schema.voices.Add("콤바인", "수류탄 준비", "수류탄 준비.", "npc/combine_soldier/vo/extractoraway.wav")
Schema.voices.Add("콤바인", "수류탄 투척", "수류탄 투척!", "npc/combine_soldier/vo/extractorisalive.wav")
Schema.voices.Add("콤바인", "미터", "미터.", "npc/combine_soldier/vo/meters.wav")

Schema.voices.Add("Dispatch", "반동 세력 활동 레벨1", "주목, 당신은 시민의 의무 레벨: 2, 시민의 의무 레벨: 2에 응하지 않아 고발되었다. 반동 세력 활동 레벨: 1로 고발되었다. 보호 기동대, 수행 코드: 근무, 무력, 작전.", "npc/overwatch/cityvoice/f_anticivil1_5_spkr.wav", true)
Schema.voices.Add("Dispatch", "반동 세력", "지상 병력, 주목: 이 지역에 반동 세력이 있다는 보고를 받았다. 코드: 감금, 제거, 진압.", "npc/overwatch/cityvoice/f_anticitizenreport_spkr.wav", true)
Schema.voices.Add("Dispatch", "반동 세력 활동", "보호 기동대, 경보: 이 지역에서 반동 세력 활동이 보이고 있다. 코드: 결집, 단속, 봉쇄.", "npc/overwatch/cityvoice/f_anticivilevidence_3_spkr.wav", true)
Schema.voices.Add("Dispatch", "정부 불응", "주목, 당신은 정부에 불응하여 고발되었다. 반동 세력 신분으로 확인되었다.", "npc/overwatch/cityvoice/f_capitalmalcompliance_spkr.wav", true)
Schema.voices.Add("Dispatch", "위치 확인", "주목, 해당 구역에 거주하는 모든 시민들은 해당 검사 위치를 확인하라.", "npc/overwatch/cityvoice/f_trainstation_assumepositions_spkr.wav", true)
Schema.voices.Add("Dispatch", "자발적 판결권", "주목, 지상 보호 기동대, 현재 자발적 판결권이 발효되었다. 현재 자발적으로 판결을 선고할 수 있다. 코드: 절단, 이민, 확인.", "npc/overwatch/cityvoice/f_protectionresponse_4_spkr.wav", true)
Schema.voices.Add("Dispatch", "시민 이전", "시민에게 알린다, 협력에 불응하면 외계로 영구히 이전되는 처벌을 받게 될 것이다.", "npc/overwatch/cityvoice/f_trainstation_offworldrelocation_spkr.wav", true)
Schema.voices.Add("Dispatch", "불법 공모", "시민에게 알린다, 방관하는 태도는 불법 공모 행위이다. 반행동을 목격할 경우 즉시 시민 보호 기동대에 신고하라.", "npc/overwatch/cityvoice/f_innactionisconspiracy_spkr.wav", true)
Schema.voices.Add("Dispatch", "시민권 박탈", "주목, 여러 반시민적 위반 행위로 인해 판결을 받았다. 시민권이 박탈되었다. 신분: 악적 존재.", "npc/overwatch/cityvoice/f_citizenshiprevoked_6_spkr.wav", true)
Schema.voices.Add("Dispatch", "보급 중단", "현 거주자 주목, 해당 구역은 반시민 활동 용인으로 고발되었다. 다섯 건의 식량 보급이 중단되었다.", "npc/overwatch/cityvoice/f_rationunitsdeduct_3_spkr.wav", true)
Schema.voices.Add("Dispatch", "기피 행동", "주목, 기피 행동은 불응 범죄와 동일하게 취급된다. 지상 보호 기동대, 경보, 코드: 격리, 차출, 집행.", "npc/overwatch/cityvoice/f_evasionbehavior_2_spkr.wav", true)
Schema.voices.Add("Dispatch", "사회 반란 레벨1", "주목, 당신은 사회 반란 레벨: 1, 사회 반란 레벨: 1로 고발되었다. 보호 기동대 병력, 수행 코드: 근무, 무력, 자정.", "npc/overwatch/cityvoice/f_sociolevel1_4_spkr.wav", true)
Schema.voices.Add("Dispatch", "비상 ID 점검", "시민에게 알린다, 비상 ID 점검을 집행 중이다. 비상 ID 점검을 진행 중이다. 지정된 위치에서 결집하라.", "npc/overwatch/cityvoice/f_trainstation_assemble_spkr.wav", true)
Schema.voices.Add("Dispatch", "판결 취소권", "주목, 모든 지상 보호 기동대, 현재 판결 취소권이 발효되었다. 임의로 극형을 집행할 수 있다.", "npc/overwatch/cityvoice/f_protectionresponse_5_spkr.wav", true)
Schema.voices.Add("Dispatch", "집계 불일치", "거주민 주목: 해당 구역에서 집계 불일치가 감지되었다. 시민 보호 기동대에게 협조하면 전체 구역에 사례가 선사된다.", "npc/overwatch/cityvoice/f_trainstation_cooperation_spkr.wav", true)
Schema.voices.Add("Dispatch", "임무 완수 실패", "지상 병력 주목, 임무 완수 실패는 곧 외계로 영구히 추방되는 처벌로 연결된다. 코드 강조: 희생, 응집, 탄압.", "npc/overwatch/cityvoice/fprison_missionfailurereminder.wav", true)
Schema.voices.Add("Dispatch", "엑소젠", "위험한 엑소젠 침입을 확인했다. 공군 감시대 증원 병력을 긴급 출동, 접근 중이다. 증원 대기.", "npc/overwatch/cityvoice/fprison_airwatchdispatched.wav", true)
Schema.voices.Add("Dispatch", "시민 감염 위험", "거주민 주목, 이 구역에는 잠재적인 시민 감염의 위험이 내포돼 있다. 신고하고, 협조하고, 결집하라.", "npc/overwatch/cityvoice/f_trainstation_inform_spkr.wav", true)
Schema.voices.Add("Dispatch", "사회 반란 레벨5", "주목, 당신은 사회 반란 레벨 5, 사회 반란 레벨 5로 고발되었다. 기피하지 말고 즉시 평결을 받으라.", "npc/overwatch/cityvoice/f_ceaseevasionlevelfive_spkr.wav", true)
Schema.voices.Add("Dispatch", "기피 대상", "보호 기동대 주목, 이 지역에 기피 대상 움직임이 감지되고 있다. 대응, 격리, 조사.", "npc/overwatch/cityvoice/f_protectionresponse_1_spkr.wav", true)
Schema.voices.Add("Dispatch", "미확인 용의자", "주목, 임시 미확인된 용의자로 분류되었다. 불이익을 받지 않으려면 즉시 시민 보호 기동대에게 신분을 확인하라.", "npc/overwatch/cityvoice/f_confirmcivilstatus_1_spkr.wav", true)
Schema.voices.Add("Dispatch", "소요 사태", "지역 시민 주목, 현재 소요 사태 진압 절차 코드가 발효되었다. 코드: 접종, 보호, 진압. 코드: 압력, 무력, 격리.", "npc/overwatch/cityvoice/f_unrestprocedure1_spkr.wav", true)
Schema.voices.Add("Dispatch", "소요 사태2", "경보, 지상 지역 시민 보호 기동대. 해당 지역에 소요 사태가 감지되었다. 결집, 집행, 진압.", "npc/overwatch/cityvoice/f_localunrest_spkr.wav", true)
Schema.voices.Add("Dispatch", "임무 완수 실패2", "지상 병력 주목, 강조한다. 지상 병력: 임무 실패는 영구한 거주지 이전으로 귀결된다. 수행 코드: 돌파, 기동, 처치.", "voices/dispatch/missionfailure_relocation.wav", true)
Schema.voices.Add("Dispatch", "중대침입", "중대한 침입 감지. 대기, 대기하라.", "voices/dispatch/crticalbreach.wav", true)
Schema.voices.Add("Dispatch", "억제기 작동중지", "이상 감지: 도시 경계 억제기의 작동 중지를 감지. 담당 부대는 해당 위치를 즉시 확인하라.", "npc/overwatch/cityvoice/fprison_restrictorsdisengaged.wav", true)
Schema.voices.Add("Dispatch", "엑소젠2", "경고, 비정상적 엑소전 활동 감지. 구역 봉쇄 절차 실행 후 보고하라.", "npc/overwatch/cityvoice/fprison_nonstandardexogen.wav", true)
Schema.voices.Add("Dispatch", "감시체계 불능", "위험, 감시 수단과 감지 체계의 비활성화가 확인되었다. 잔여 담당 병력은 봉쇄 상태를 보고하라.", "npc/overwatch/cityvoice/fprison_detectionsystemsout.wav", true)
Schema.voices.Add("Dispatch", "보안우회", "위험, 악성 보안 체계 우회가 감지. 다방면적 보안 체계 변형이 감지. 살균과 봉쇄 체계에 결함이 발생하였을 가능성 존재.", "npc/overwatch/cityvoice/fprison_interfacebypass.wav", true)
Schema.voices.Add("Dispatch", "코드 수호", "수행 코드: 수호, 핵심. 이동.", "voices/dispatch/responsecode_shield.wav", true)
Schema.voices.Add("Dispatch", "제한구역1", "주목, 이 구역으로의 진입은 금지되어 있다. 기소를 위해 시민 보호 기동대 병력이 배치되었다.", "voices/dispatch/restrictedblock_deployment.wav", true)
Schema.voices.Add("Dispatch", "제한구역2", "주목, 이 구역으로의 진입은 허가되어 있지 않다. 이 방송이 대상하는 자는 반사회 활동 중임을 의미한다.", "voices/dispatch/restrictedblock_warning.wav", true)
Schema.voices.Add("Dispatch", "재정비", "지상 병력 주목, 재정비가 진행 중이다. 부대 재정비 코드: 반응. 조사. 제거. 우선 사항: 지시이행.", "voices/dispatch/readministration.wav", true)
Schema.voices.Add("Dispatch", "중요도 1 목표물", "지정된 중요도 1 구역을 공격하라, 무기 사용 무제한. 용의자가 중요도 1 목표물로 설정되었다. 발견 즉시 사살하라.", "voices/dispatch/primaryone_objective.wav", true)
Schema.voices.Add("Dispatch", "용의자레벨5", "주목, 당신은 사회 반란 레벨 5 범죄 혐의로 고발되었다. 파견된 병력의 지시에 순응하라. 지상 병력 주목: 임무개시. 코드: 교전, 고립, 무력화.", "voices/dispatch/level5_anticivil.wav", true)
Schema.voices.Add("Dispatch", "현재병력배치", "최대보안경고. 작전수행 코드: 5-1-2-9. 병력배치 코드: 5-1-2-9.", "voices/dispatch/concurrent_deployment.wav", true)
Schema.voices.Add("Dispatch", "기피 행동2", "지상 병력 주목. 반사회 속성의 고의적 불안야기 활동이 감지되었다. 수행 코드: 교전, 평정, 확인.", "voices/dispatch/anticivil_evading.wav", true)
Schema.voices.Add("Dispatch", "중대사회반란", "지상 병력 주목. 중대한 사회반란 사태가 감지되었다. 최우선적으로 49, 64, 77 구역에 공병대를 배치하라.", "voices/dispatch/civil_insurrection.wav", true)
Schema.voices.Add("Dispatch", "코드 공허", "지상 병력 주목. 지휘관들에게 전달한다. 비상 코드: 공허.", "voices/dispatch/emergencyvoid.wav", true)
Schema.voices.Add("Dispatch", "접근제한", "주목, 이 구역은 접근이 제한되어 있다. 반사회적 약탈 행위는 즉시 중대 기소 사유로 작용할 것이다.", "voices/dispatch/access_restricted.wav", true)
Schema.voices.Add("Dispatch", "시민알림", "시민에게 알린다: 안정적인 사회는 신속하고 정확한 감독을 필요로 한다. 동료 시민이 사회의 안정을 위협하는 것을 방치하지 말라.", "voices/dispatch/citizen_reminder2.wav", true)


Schema.voices.Add("Dispatch Radio", "404", "404 구역.", "npc/overwatch/radiovoice/404zone.wav")
Schema.voices.Add("Dispatch Radio", "공범자 활동", "보호 기동대, 구역 내 공범자가 활동 중이다.", "npc/overwatch/radiovoice/accomplicesoperating.wav")
Schema.voices.Add("Dispatch Radio", "집행하라", "집행하라.", "npc/overwatch/radiovoice/administer.wav")
Schema.voices.Add("Dispatch Radio", "공군 감시대", "공군 감시대, 이 위치에 활동이 없다.", "npc/overwatch/radiovoice/airwatchcopiesnoactivity.wav")
Schema.voices.Add("Dispatch Radio", "공군 감시대2", "공군 감시대, 불일치 보고.", "npc/overwatch/radiovoice/airwatchreportspossiblemiscount.wav")
Schema.voices.Add("Dispatch Radio", "62", "62 경보.", "npc/overwatch/radiovoice/alarms62.wav")
Schema.voices.Add("Dispatch Radio", "코드 3", "모든 병력 응답하라, 코드 3.", "npc/overwatch/radiovoice/allteamsrespondcode3.wav")
Schema.voices.Add("Dispatch Radio", "전진", "모든 병력, 앞으로 전진하라.", "npc/overwatch/radiovoice/allunitsapplyforwardpressure.wav")
Schema.voices.Add("Dispatch Radio", "모든 병력", "모든 병력.", "npc/overwatch/radiovoice/allunitsat.wav")
Schema.voices.Add("Dispatch Radio", "증인 제거", "모든 병력, 증인 제거 시행하라.", "npc/overwatch/radiovoice/allunitsbeginwhitnesssterilization.wav")
Schema.voices.Add("Dispatch Radio", "243", "243 용의자, 보이는 즉시 보고하라.", "npc/overwatch/radiovoice/allunitsbolfor243suspect.wav")
Schema.voices.Add("Dispatch Radio", "최종 평결2", "모든 병력은 즉시 최종 평결을 전달하라.", "npc/overwatch/radiovoice/allunitsdeliverterminalverdict.wav")
Schema.voices.Add("Dispatch Radio", "코드 12", "모든 병력, 코드 12로 돌아가라.", "npc/overwatch/radiovoice/allunitsreturntocode12.wav")
Schema.voices.Add("Dispatch Radio", "평결 코드", "모든 병력, 평결 코드.", "npc/overwatch/radiovoice/allunitsverdictcodeis.wav")
Schema.voices.Add("Dispatch Radio", "평결 코드 용의자", "모든 병력, 평결 코드: 용의자.", "npc/overwatch/radiovoice/allunitsverdictcodeonsuspect.wav")
Schema.voices.Add("Dispatch Radio", "절단", "절단.", "npc/overwatch/radiovoice/amputate.wav")
Schema.voices.Add("Dispatch Radio", "반동 세력", "반동 세력.", "npc/overwatch/radiovoice/anticitizen.wav")
Schema.voices.Add("Dispatch Radio", "예방 배급량", "필요 예방 배급량은 지금부로 3 밀리그램.", "npc/overwatch/radiovoice/antifatigueration3mg.wav")
Schema.voices.Add("Dispatch Radio", "적용", "적용.", "npc/overwatch/radiovoice/apply.wav")
Schema.voices.Add("Dispatch Radio", "243 습격", "243, 보호 기동대 습격.", "npc/overwatch/radiovoice/assault243.wav")
Schema.voices.Add("Dispatch Radio", "27", "27, 범죄 시도.", "npc/overwatch/radiovoice/attemptedcrime27.wav")
Schema.voices.Add("Dispatch Radio", "주목", "주목.", "npc/overwatch/radiovoice/attention.wav")
Schema.voices.Add("Dispatch Radio", "고발됨", "주목, 당신은 고발되었다.", "npc/overwatch/radiovoice/attentionyouhavebeenchargedwith.wav")
Schema.voices.Add("Dispatch Radio", "10-0", "10-0, 수색 시작.", "npc/overwatch/radiovoice/beginscanning10-0.wav")
Schema.voices.Add("Dispatch Radio", "구역", "구역.", "npc/overwatch/radiovoice/block.wav")
Schema.voices.Add("Dispatch Radio", "불순종", "중대 불순종.", "npc/overwatch/radiovoice/capitalmalcompliance.wav")
Schema.voices.Add("Dispatch Radio", "제거", "제거.", "npc/overwatch/radiovoice/cauterize.wav")
Schema.voices.Add("Dispatch Radio", "시민", "시민.", "npc/overwatch/radiovoice/citizen.wav")
Schema.voices.Add("Dispatch Radio", "임의 선고 완결", "모든 보호 기동대 병력, 임의 선고 완결하라.", "npc/overwatch/radiovoice/completesentencingatwill.wav")
Schema.voices.Add("Dispatch Radio", "사형 선고 구역", "사형 선고 구역.", "npc/overwatch/radiovoice/condemnedzone.wav")
Schema.voices.Add("Dispatch Radio", "UPI2", "팀, UPI 경보 확인.", "npc/overwatch/radiovoice/confirmupialert.wav")
Schema.voices.Add("Dispatch Radio", "통제 구역", "집단, 통제 구역.", "npc/overwatch/radiovoice/controlsection.wav")
Schema.voices.Add("Dispatch Radio", "침입", "63, 범죄자 침입.", "npc/overwatch/radiovoice/criminaltrespass63.wav")
Schema.voices.Add("Dispatch Radio", "방어자", "방어자.", "npc/overwatch/radiovoice/defender.wav")
Schema.voices.Add("Dispatch Radio", "제한된 구역", "제한된 구역.", "npc/overwatch/radiovoice/deservicedarea.wav")
Schema.voices.Add("Dispatch Radio", "병력 전멸", "상병, 사회 보호 기동대 병력 전멸.", "npc/overwatch/radiovoice/destrutionofcpt.wav")
Schema.voices.Add("Dispatch Radio", "반사회2", "불안정한 반사회 불복종.", "npc/overwatch/radiovoice/devisivesociocidal.wav")
Schema.voices.Add("Dispatch Radio", "시민 분열", "전체 시민들의 분열.", "npc/overwatch/radiovoice/disassociationfromcivic.wav")
Schema.voices.Add("Dispatch Radio", "647-E", "647-E, 인력에서 해제.", "npc/overwatch/radiovoice/disengaged647e.wav")
Schema.voices.Add("Dispatch Radio", "분배 구역", "분배 구역.", "npc/overwatch/radiovoice/distributionblock.wav")
Schema.voices.Add("Dispatch Radio", "10-103", "10-103, 정신적인 괴리로 혼란.", "npc/overwatch/radiovoice/disturbancemental10-103m.wav")
Schema.voices.Add("Dispatch Radio", "415", "415, 시민 불화.", "npc/overwatch/radiovoice/disturbingunity415.wav")
Schema.voices.Add("Dispatch Radio", "증거", "증거.", "npc/overwatch/radiovoice/document.wav")
Schema.voices.Add("Dispatch Radio", "8", "8.", "npc/overwatch/radiovoice/eight.wav")
Schema.voices.Add("Dispatch Radio", "응집력 없음", "연루된 보호 기동대 응집력 없음.", "npc/overwatch/radiovoice/engagingteamisnoncohesive.wav")
Schema.voices.Add("Dispatch Radio", "검사", "검사.", "npc/overwatch/radiovoice/examine.wav")
Schema.voices.Add("Dispatch Radio", "외부 관할권", "외부 관할권.", "npc/overwatch/radiovoice/externaljurisdiction.wav")
Schema.voices.Add("Dispatch Radio", "순응 실패", "시민의 의지 순응 실패.", "npc/overwatch/radiovoice/failuretocomply.wav")
Schema.voices.Add("Dispatch Radio", "폭동 진압 실패", "진압 팀, 배치된 지역에 폭동 진압이 실패하면 팀 처리 및 재활용이 집행될 것이다.", "npc/overwatch/radiovoice/failuretotreatoutbreak.wav")
Schema.voices.Add("Dispatch Radio", "최종 평결", "최종 평결 집행하라.", "npc/overwatch/radiovoice/finalverdictadministered.wav")
Schema.voices.Add("Dispatch Radio", "5", "5.", "npc/overwatch/radiovoice/five.wav")
Schema.voices.Add("Dispatch Radio", "스카이쉴드", "스카이쉴드.", "npc/overwatch/radiovoice/fmil_region 073.wav")
Schema.voices.Add("Dispatch Radio", "4", "4.", "npc/overwatch/radiovoice/four.wav")
Schema.voices.Add("Dispatch Radio", "17-F", "17-F, 탈주자 이탈.", "npc/overwatch/radiovoice/fugitive17f.wav")
Schema.voices.Add("Dispatch Radio", "안정지수", "50% 안정지수.", "npc/overwatch/radiovoice/halfrankpoints.wav")
Schema.voices.Add("Dispatch Radio", "재생산 크레디트", "50% 재생산 크레디트.", "npc/overwatch/radiovoice/halfreproductioncredits.wav")
Schema.voices.Add("Dispatch Radio", "히어로", "히어로.", "npc/overwatch/radiovoice/hero.wav")
Schema.voices.Add("Dispatch Radio", "최우선 지역", "최우선 지역.", "npc/overwatch/radiovoice/highpriorityregion.wav")
Schema.voices.Add("Dispatch Radio", "95", "95, 불법 소지.", "npc/overwatch/radiovoice/illegalcarrying95.wav")
Schema.voices.Add("Dispatch Radio", "63", "63, 불법 작전 지시.", "npc/overwatch/radiovoice/illegalinoperation63s.wav")
Schema.voices.Add("Dispatch Radio", "즉시 절단", "즉시 절단.", "npc/overwatch/radiovoice/immediateamputation.wav")
Schema.voices.Add("Dispatch Radio", "반사회3", "불안정한 반사회 불복종.", "npc/overwatch/radiovoice/incitingpopucide.wav")
Schema.voices.Add("Dispatch Radio", "산업 구역", "산업 구역.", "npc/overwatch/radiovoice/industrialzone.wav")
Schema.voices.Add("Dispatch Radio", "감염", "감염.", "npc/overwatch/radiovoice/infection.wav")
Schema.voices.Add("Dispatch Radio", "감염 구역", "감염 구역.", "npc/overwatch/radiovoice/infestedzone.wav")
Schema.voices.Add("Dispatch Radio", "주입", "주입.", "npc/overwatch/radiovoice/inject.wav")
Schema.voices.Add("Dispatch Radio", "접목", "접목.", "npc/overwatch/radiovoice/innoculate.wav")
Schema.voices.Add("Dispatch Radio", "진행 중", "진행 중.", "npc/overwatch/radiovoice/inprogress.wav")
Schema.voices.Add("Dispatch Radio", "차단", "차단.", "npc/overwatch/radiovoice/intercede.wav")
Schema.voices.Add("Dispatch Radio", "결합", "결합.", "npc/overwatch/radiovoice/interlock.wav")
Schema.voices.Add("Dispatch Radio", "조사", "조사.", "npc/overwatch/radiovoice/investigate.wav")
Schema.voices.Add("Dispatch Radio", "조사 및 보고", "조사 및 보고하라.", "npc/overwatch/radiovoice/investigateandreport.wav")
Schema.voices.Add("Dispatch Radio", "현재", "현재.", "npc/overwatch/radiovoice/isnow.wav")
Schema.voices.Add("Dispatch Radio", "격리", "격리.", "npc/overwatch/radiovoice/isolate.wav")
Schema.voices.Add("Dispatch Radio", "주리", "주리.", "npc/overwatch/radiovoice/jury.wav")
Schema.voices.Add("Dispatch Radio", "킹", "킹.", "npc/overwatch/radiovoice/king.wav")
Schema.voices.Add("Dispatch Radio", "격리된 사상자", "진압 팀 리더 주목, 이 서비스 병력은 격리된 사상자 수를 모두 강제 처리, 사례 지급 또는 제거 처리하여 보고하라.", "npc/overwatch/radiovoice/leadersreportratios.wav")
Schema.voices.Add("Dispatch Radio", "레벨 5", "레벨 5, 반동 세력 활동.", "npc/overwatch/radiovoice/level5anticivilactivity.wav")
Schema.voices.Add("Dispatch Radio", "라인", "라인.", "npc/overwatch/radiovoice/line.wav")
Schema.voices.Add("Dispatch Radio", "위치 고정", "위치 고정.", "npc/overwatch/radiovoice/lock.wav")
Schema.voices.Add("Dispatch Radio", "관할 위치 감금", "보호 기동대, 관할 위치 감금. 희생 코드.", "npc/overwatch/radiovoice/lockdownlocationsacrificecode.wav")
Schema.voices.Add("Dispatch Radio", "기동대 사망", "보호 기동대에 대한 생체 신호 실패.", "npc/overwatch/radiovoice/lostbiosignalforunit.wav")
Schema.voices.Add("Dispatch Radio", "9", "9.", "npc/overwatch/radiovoice/nine.wav")
Schema.voices.Add("Dispatch Radio", "반동 세력2", "반동 세력.", "npc/overwatch/radiovoice/noncitizen.wav")
Schema.voices.Add("Dispatch Radio", "패트롤 영역 없음", "패트롤 영역 없음.", "npc/overwatch/radiovoice/nonpatrolregion.wav")
Schema.voices.Add("Dispatch Radio", "51", "51, 방화 금지.", "npc/overwatch/radiovoice/nonsanctionedarson51.wav")
Schema.voices.Add("Dispatch Radio", "경관", "경관.", "npc/overwatch/radiovoice/officerat.wav")
Schema.voices.Add("Dispatch Radio", "수사 종결", "장교 용의자 수사 종결.", "npc/overwatch/radiovoice/officerclosingonsuspect.wav")
Schema.voices.Add("Dispatch Radio", "1", "1.", "npc/overwatch/radiovoice/one.wav")
Schema.voices.Add("Dispatch Radio", "외지 구역", "외지 구역.", "npc/overwatch/radiovoice/outlandzone.wav")
Schema.voices.Add("Dispatch Radio", "패트롤", "패트롤.", "npc/overwatch/radiovoice/patrol.wav")
Schema.voices.Add("Dispatch Radio", "시민 정치 진압", "주목, 보호 기동대. 시민 정치 진압 지시가 한계에 다다랐다.", "npc/overwatch/radiovoice/politistablizationmarginal.wav")
Schema.voices.Add("Dispatch Radio", "69", "69, 자원 소유.", "npc/overwatch/radiovoice/posession69.wav")
Schema.voices.Add("Dispatch Radio", "미성숙한 임무 종결", "미성숙한 임무 종결로 인한 결과.", "npc/overwatch/radiovoice/prematuremissiontermination.wav")
Schema.voices.Add("Dispatch Radio", "선고 준비", "최종 판결 선고 준비.", "npc/overwatch/radiovoice/prepareforfinalsentencing.wav")
Schema.voices.Add("Dispatch Radio", "투입 준비", "모든 지역 보호 기동대 병력, 투입 준비.", "npc/overwatch/radiovoice/preparetoinnoculate.wav")
Schema.voices.Add("Dispatch Radio", "평결 수락 준비", "평결 수락 준비.", "npc/overwatch/radiovoice/preparetoreceiveverdict.wav")
Schema.voices.Add("Dispatch Radio", "사진", "주목, 반동 세력 한 명의 정보 다운로드 준비.", "npc/overwatch/radiovoice/preparevisualdownload.wav")
Schema.voices.Add("Dispatch Radio", "보호", "보호.", "npc/overwatch/radiovoice/preserve.wav")
Schema.voices.Add("Dispatch Radio", "압력", "압력.", "npc/overwatch/radiovoice/pressure.wav")
Schema.voices.Add("Dispatch Radio", "생산 구역", "생산 구역.", "npc/overwatch/radiovoice/productionblock.wav")
Schema.voices.Add("Dispatch Radio", "불안 조성", "공동체 불안 조성.", "npc/overwatch/radiovoice/promotingcommunalunrest.wav")
Schema.voices.Add("Dispatch Radio", "집행", "집행.", "npc/overwatch/radiovoice/prosecute.wav")
Schema.voices.Add("Dispatch Radio", "507", "507, 공개 불응.", "npc/overwatch/radiovoice/publicnoncompliance507.wav")
Schema.voices.Add("Dispatch Radio", "퀵", "퀵.", "npc/overwatch/radiovoice/quick.wav")
Schema.voices.Add("Dispatch Radio", "사회식 재조정", "팀, 사회식 재조정.", "npc/overwatch/radiovoice/recalibratesocioscan.wav")
Schema.voices.Add("Dispatch Radio", "ㄴㄴ", "불일치하는 데이터를 수신하고 있다.", "npc/overwatch/radiovoice/recievingconflictingdata.wav")
Schema.voices.Add("Dispatch Radio", "99", "99, 무모한 작전 지시.", "npc/overwatch/radiovoice/recklessoperation99.wav")
Schema.voices.Add("Dispatch Radio", "증원 병력 코드 3", "증원 병력, 코드 3.", "npc/overwatch/radiovoice/reinforcementteamscode3.wav")
Schema.voices.Add("Dispatch Radio", "잔존 병력 봉쇄", "잔존 병력, 봉쇄.", "npc/overwatch/radiovoice/remainingunitscontain.wav")
Schema.voices.Add("Dispatch Radio", "자발적인 재생산 시뮬레이션", "고위 리더, 알림. 100 격리 크레디트는 자발적인 재생산 시뮬레이션에 적합하다.", "npc/overwatch/radiovoice/reminder100credits.wav")
Schema.voices.Add("Dispatch Radio", "메모리 교체", "알림. 메모리 교체는 고위 계층 특권을 이행하는 1단계이다.", "npc/overwatch/radiovoice/remindermemoryreplacement.wav")
Schema.voices.Add("Dispatch Radio", "보고하라2", "지역 보호 기동대 병력, 보고하라.", "npc/overwatch/radiovoice/reporton.wav")
Schema.voices.Add("Dispatch Radio", "보고하라", "지역 보호 기동대 병력, 보고하라.", "npc/overwatch/radiovoice/reportplease.wav")
Schema.voices.Add("Dispatch Radio", "용도 변경 지역", "용도 변경 지역.", "npc/overwatch/radiovoice/repurposedarea.wav")
Schema.voices.Add("Dispatch Radio", "거주 구역", "거주 구역", "npc/overwatch/radiovoice/residentialblock.wav")
Schema.voices.Add("Dispatch Radio", "148", "148, 체포 저항.", "npc/overwatch/radiovoice/resistingpacification148.wav")
Schema.voices.Add("Dispatch Radio", "응답하라", "응답하라.", "npc/overwatch/radiovoice/respond.wav")
Schema.voices.Add("Dispatch Radio", "제한된 구역", "제한된 구역.", "npc/overwatch/radiovoice/restrictedblock.wav")
Schema.voices.Add("Dispatch Radio", "제한된 봉쇄", "제한된 봉쇄 진행 중.", "npc/overwatch/radiovoice/restrictedincursioninprogress.wav")
Schema.voices.Add("Dispatch Radio", "사례 통지", "사례 통지. 보호 기동대 구성원, 당신의 가족 결성력이 보장된다.", "npc/overwatch/radiovoice/rewardnotice.wav")
Schema.voices.Add("Dispatch Radio", "404", "404, 폭동.", "npc/overwatch/radiovoice/riot404.wav")
Schema.voices.Add("Dispatch Radio", "롤러", "롤러.", "npc/overwatch/radiovoice/roller.wav")
Schema.voices.Add("Dispatch Radio", "검색", "검색.", "npc/overwatch/radiovoice/search.wav")
Schema.voices.Add("Dispatch Radio", "섹터", "섹터.", "npc/overwatch/radiovoice/sector.wav")
Schema.voices.Add("Dispatch Radio", "복무", "복무.", "npc/overwatch/radiovoice/serve.wav")
Schema.voices.Add("Dispatch Radio", "7", "7.", "npc/overwatch/radiovoice/seven.wav")
Schema.voices.Add("Dispatch Radio", "6", "6.", "npc/overwatch/radiovoice/six.wav")
Schema.voices.Add("Dispatch Radio", "사회적 분열", "사회적 분열이 진행 중이다. 응답하라.", "npc/overwatch/radiovoice/socialfractureinprogress.wav")
Schema.voices.Add("Dispatch Radio", "반사회", "반사회.", "npc/overwatch/radiovoice/sociocide.wav")
Schema.voices.Add("Dispatch Radio", "끝", "사회 안전이 회복되었다.", "npc/overwatch/radiovoice/sociostabilizationrestored.wav")
Schema.voices.Add("Dispatch Radio", "진압 관할권", "진압 관할권.", "npc/overwatch/radiovoice/stabilizationjurisdiction.wav")
Schema.voices.Add("Dispatch Radio", "스테이션 구역", "스테이션 구역.", "npc/overwatch/radiovoice/stationblock.wav")
Schema.voices.Add("Dispatch Radio", "243 용의자", "모든 병력은 243 용의자 상태를 보고하라.", "npc/overwatch/radiovoice/statuson243suspect.wav")
Schema.voices.Add("Dispatch Radio", "격리", "격리.", "npc/overwatch/radiovoice/sterilize.wav")
Schema.voices.Add("Dispatch Radio", "스틱", "스틱.", "npc/overwatch/radiovoice/stick.wav")
Schema.voices.Add("Dispatch Radio", "스톰시스템", "스톰시스템.", "npc/overwatch/radiovoice/stormsystem.wav")
Schema.voices.Add("Dispatch Radio", "표적", "표적.", "npc/overwatch/radiovoice/subject.wav")
Schema.voices.Add("Dispatch Radio", "187", "용의자는 현재 187이다.", "npc/overwatch/radiovoice/suspectisnow187.wav")
Schema.voices.Add("Dispatch Radio", "악성", "용의자는 악성으로 판결되었다. 평결 코드.", "npc/overwatch/radiovoice/suspectmalignantverdictcodeis.wav")
Schema.voices.Add("Dispatch Radio", "중지", "중지.", "npc/overwatch/radiovoice/suspend.wav")
Schema.voices.Add("Dispatch Radio", "협상 중지", "협상 중지.", "npc/overwatch/radiovoice/suspendnegotiations.wav")
Schema.voices.Add("Dispatch Radio", "전술 3", "모든 병력, 전술 3으로 변경.", "npc/overwatch/radiovoice/switchcomtotac3.wav")
Schema.voices.Add("Dispatch Radio", "전술 5", "모든 병력, 전술 5으로 변경. 관할 사령관에게 보고하라.", "npc/overwatch/radiovoice/switchtotac5reporttocp.wav")
Schema.voices.Add("Dispatch Radio", "탭", "탭.", "npc/overwatch/radiovoice/tap.wav")
Schema.voices.Add("Dispatch Radio", "보고하라3", "지역 시민 보호 기동대, 상태 보고하라.", "npc/overwatch/radiovoice/teamsreportstatus.wav")
Schema.voices.Add("Dispatch Radio", "사형 집행", "사형 집행.", "npc/overwatch/radiovoice/terminalprosecution.wav")
Schema.voices.Add("Dispatch Radio", "최종 제한 구역", "최종 제한 구역.", "npc/overwatch/radiovoice/terminalrestrictionzone.wav")
Schema.voices.Add("Dispatch Radio", "51-B", "51-B, 위험 상태.", "npc/overwatch/radiovoice/threattoproperty51b.wav")
Schema.voices.Add("Dispatch Radio", "3", "3.", "npc/overwatch/radiovoice/three.wav")
Schema.voices.Add("Dispatch Radio", "통과 구역", "통과 구역.", "npc/overwatch/radiovoice/transitblock.wav")
Schema.voices.Add("Dispatch Radio", "2", "2.", "npc/overwatch/radiovoice/two.wav")
Schema.voices.Add("Dispatch Radio", "연합", "연합.", "npc/overwatch/radiovoice/union.wav")
Schema.voices.Add("Dispatch Radio", "병역 중단", "병력, 병역 중단.", "npc/overwatch/radiovoice/unitdeserviced.wav")
Schema.voices.Add("Dispatch Radio", "병력 침입", "병력 침입.", "npc/overwatch/radiovoice/unitdownat.wav")
Schema.voices.Add("Dispatch Radio", "603", "603, 불법 침입.", "npc/overwatch/radiovoice/unlawfulentry603.wav")
Schema.voices.Add("Dispatch Radio", "UPI", "UPI.", "npc/overwatch/radiovoice/upi.wav")
Schema.voices.Add("Dispatch Radio", "바이스", "바이스.", "npc/overwatch/radiovoice/vice.wav")
Schema.voices.Add("Dispatch Radio", "빅터", "빅터.", "npc/overwatch/radiovoice/victor.wav")
Schema.voices.Add("Dispatch Radio", "시민 신뢰 침해", "시민 신뢰 침해.", "npc/overwatch/radiovoice/violationofcivictrust.wav")
Schema.voices.Add("Dispatch Radio", "오염된 강", "오염된 강.", "npc/overwatch/radiovoice/wasteriver.wav")
Schema.voices.Add("Dispatch Radio", "94", "94, 무기.", "npc/overwatch/radiovoice/weapon94.wav")
Schema.voices.Add("Dispatch Radio", "인력 구치 허브", "인력 구치 허브.", "npc/overwatch/radiovoice/workforceintake.wav")
Schema.voices.Add("Dispatch Radio", "엑스레이", "엑스레이.", "npc/overwatch/radiovoice/xray.wav")
Schema.voices.Add("Dispatch Radio", "옐로우", "옐로우.", "npc/overwatch/radiovoice/yellow.wav")
Schema.voices.Add("Dispatch Radio", "148 243 245", "최종 위반 행위: 148, 243, 245로 인해 고발되었다.", "npc/overwatch/radiovoice/youarechargedwithterminal.wav")
Schema.voices.Add("Dispatch Radio", "유죄 판결", "시민 보호 기동대가 유죄 판결을 내렸다.", "npc/overwatch/radiovoice/youarejudgedguilty.wav")
Schema.voices.Add("Dispatch Radio", "0", "0.", "npc/overwatch/radiovoice/zero.wav")
Schema.voices.Add("Dispatch Radio", "구역", "구역.", "npc/overwatch/radiovoice/zone.wav")

do
	Schema.voices.AddClass("콤바인", function(client)
		return client:IsCombine() and client:Team() != FACTION_OVERWATCH
	end, {"ic", "w", "y", "radio", "radio_eavesdrop"})

	Schema.voices.AddClass("Dispatch", function(client)
		return client:IsDispatch()
	end, "dispatch")

	Schema.voices.AddClass("Dispatch Radio", function(client)
		return client:IsDispatch()
	end, "dispatch_radio")

	Schema.voices.AddClass("Ordinal", function(client)
		return client:IsCombine() and client:Team() == FACTION_EOW
	end, {"ic", "w", "y", "radio", "radio_eavesdrop"})
end
